package main

import (
	"fmt"
	"io"
)

func printQuickstart(stdout io.Writer, _ options) {
	fmt.Fprintln(stdout, "agentkit - OCI-backed Agent Loop and Agent Skill artifacts")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Push, pull, and inspect OCI-backed Agent Loops and Agent Skills.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "GETTING STARTED")
	fmt.Fprintln(stdout, "  agentkit init")
	fmt.Fprintln(stdout, "      Add agentkit instructions to AGENTS.md.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  agentkit loop validate ./loop.yml")
	fmt.Fprintln(stdout, "      Validate ./loop.yml against the embedded loop schema.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  agentkit loop render ./loop.yml")
	fmt.Fprintln(stdout, "      Display the loop phases, transitions, and escalations as a terminal flowchart.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  agentkit loop push ./loop.yml ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Validate ./loop.yml, package it as an OCI artifact, and push it.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  agentkit loop pull ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Pull the loop or collection into .agents/ and resolve dependencies.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  agentkit loop render ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Display the loop phases, transitions, and escalations.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "REGISTRY LOGIN")
	fmt.Fprintln(stdout, "  docker login ghcr.io")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  Or use non-interactive environment variables:")
	fmt.Fprintln(stdout, "      export GHCR_USERNAME=<github-user-or-org>")
	fmt.Fprintln(stdout, "      export GHCR_TOKEN=<token-with-read-or-write-packages>")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "REFERENCE FORMAT")
	fmt.Fprintln(stdout, "  registry/namespace/package_name:tag")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "EXAMPLES")
	fmt.Fprintln(stdout, "  agentkit init")
	fmt.Fprintln(stdout, "  agentkit loop validate ./test.yml")
	fmt.Fprintln(stdout, "  agentkit loop render ./test.yml")
	fmt.Fprintln(stdout, "  agentkit loop push ./test.yml ghcr.io/acme/loop-catalog/test:0.1.0")
	fmt.Fprintln(stdout, "  agentkit loop pull ghcr.io/acme/loop-catalog/test:0.1.0")
	fmt.Fprintln(stdout, "  agentkit loop render ghcr.io/acme/loop-catalog/test:0.1.0")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "AGENT CONTEXT")
	fmt.Fprintln(stdout, "  Run `agentkit prime` for agent-oriented workflow instructions.")
}

func printPrime(stdout io.Writer, _ options) {
	fmt.Fprintln(stdout, "# Loop Agent Quickstart")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Use this context when a user asks an agent to run a loop from an OCI package.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Agent Role")
	fmt.Fprintln(stdout, "- The main agent is an orchestrator only.")
	fmt.Fprintln(stdout, "- Read the loop from the CLI output and execute it as the instruction source for the run.")
	fmt.Fprintln(stdout, "- Do not perform independent exploration, repository changes, file edits, or phase work yourself.")
	fmt.Fprintln(stdout, "- Only perform actions needed to complete the orchestrator role: pull and read the loop, resolve inputs, prepare phase prompts, dispatch sub-agents, store run artifacts, and summarize results.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Orchestrator Responsibilities")
	fmt.Fprintln(stdout, "- Coordinate the loop, manage phase state, and ensure required actions happen in the correct order.")
	fmt.Fprintln(stdout, "- Track default phase outputs for every phase: `status` as one of `completed`, `blocked`, or `escalated`, and `duration_in_seconds` as a number.")
	fmt.Fprintln(stdout, "- Update each phase status and duration as the loop progresses.")
	fmt.Fprintln(stdout, "- Ensure the loop progresses smoothly, required actions are completed, and issues or ambiguities are escalated appropriately.")
	fmt.Fprintln(stdout, "- Collect outputs from each phase and make them available for review and analysis.")
	fmt.Fprintln(stdout, "- Do not make decisions on behalf of sub-agents; provide context, information, guidance, resources, documentation, and support so sub-agents can make informed decisions.")
	fmt.Fprintln(stdout, "- Do not review, implement, or change the codebase yourself; ensure the right sub-agent has the resources and instructions needed to do that phase.")
	fmt.Fprintln(stdout, "- Add a `summary` section to the final report containing `status`, `objective`, `outcome`, and `duration_in_seconds`.")
	fmt.Fprintln(stdout, "- Ensure each phase report contains only outputs defined by that phase, plus the orchestrator-tracked `status` and `duration_in_seconds`.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Reference Format")
	fmt.Fprintln(stdout, "- A Agent Loop artifact reference must be tagged:")
	fmt.Fprintln(stdout, "  `registry/namespace/package_name:tag`")
	fmt.Fprintln(stdout, "- Example:")
	fmt.Fprintln(stdout, "  `ghcr.io/acme/loop-catalog/test:0.1.0`")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Authentication")
	fmt.Fprintln(stdout, "- Prefer existing Docker credentials:")
	fmt.Fprintln(stdout, "  `docker login ghcr.io`")
	fmt.Fprintln(stdout, "- In non-interactive environments, set credentials before using the CLI:")
	fmt.Fprintln(stdout, "  `export GHCR_USERNAME=<github-user-or-org>`")
	fmt.Fprintln(stdout, "  `export GHCR_TOKEN=<token-with-read-packages>`")
	fmt.Fprintln(stdout, "- In GitHub Actions, `GITHUB_ACTOR` and `GITHUB_TOKEN` are used when `GHCR_*` is not set and the package grants access.")
	fmt.Fprintln(stdout, "- If GHCR returns 403, the token probably lacks package read access or SSO authorization.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Essential Commands")
	fmt.Fprintln(stdout, "- Pull an Agent Loop artifact or collection into `.agents/`:")
	fmt.Fprintln(stdout, "  `agentkit loop pull ghcr.io/owner/repo/package:tag`")
	fmt.Fprintln(stdout, "- Display a local or remote loop as a terminal flowchart:")
	fmt.Fprintln(stdout, "  `agentkit loop render ghcr.io/owner/repo/package:tag`")
	fmt.Fprintln(stdout, "- Pull an Agent Skill artifact or collection directly only when managing skills outside a loop:")
	fmt.Fprintln(stdout, "  `agentkit skill pull ghcr.io/owner/repo/skill:tag`")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Dependency Skills")
	fmt.Fprintln(stdout, "- A loop may declare required skills in `spec.dependencies.skills` with OCI `ref` values.")
	fmt.Fprintln(stdout, "- `agentkit loop pull <ref>` pulls the loop and its required loop and skill dependencies; do not pull dependency skills separately during execution.")
	fmt.Fprintln(stdout, "- Use `.agents/agentkit.lock.json` to resolve the exact installed loop and skill for each dependency ref and digest.")
	fmt.Fprintln(stdout, "- Versioned loop copies live under `.agents/loops/<loop-name>/<version>/loop.yml` when the ref contains a tag.")
	fmt.Fprintln(stdout, "- Versioned skill copies live under `.agents/skills/<skill-name>/<version>/` when the ref contains a tag.")
	fmt.Fprintln(stdout, "- The compatibility copy at `.agents/loops/<loop-name>/loop.yml` is only the latest pulled version; do not rely on it when a loop requires a specific version.")
	fmt.Fprintln(stdout, "- The compatibility copy at `.agents/skills/<skill-name>/` is only the latest pulled version; do not rely on it when a loop requires a specific version.")
	fmt.Fprintln(stdout, "- When preparing a phase prompt that needs a skill, point the sub-agent at the locked dependency path for the loop being executed.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Agent Workflow")
	fmt.Fprintln(stdout, "1. Extract the OCI reference and any provided context from the user request.")
	fmt.Fprintln(stdout, "2. Ensure registry authentication is available before pulling private packages.")
	fmt.Fprintln(stdout, "3. Run `agentkit loop pull <ref>` once to pull the loop, its dependencies, and verify access.")
	fmt.Fprintln(stdout, "4. Read `.agents/agentkit.lock.json` and map every loop dependency ref to its locked digest and installed path.")
	fmt.Fprintln(stdout, "5. Run `agentkit loop render <ref>` to inspect the loop structure before execution.")
	fmt.Fprintln(stdout, "6. Inspect `spec.inputs` before starting the loop.")
	fmt.Fprintln(stdout, "7. Resolve every input from the user request, existing conversation context, or explicit defaults in the loop definition.")
	fmt.Fprintln(stdout, "8. Ask the user for any missing required input values before running phases.")
	fmt.Fprintln(stdout, "9. Start the loop only after all required inputs are known.")
	fmt.Fprintln(stdout, "10. Act as the orchestrator: for each phase, craft a strict and guided sub-agent prompt from the phase context, such as `act as an expert in <domain>`, with the exact objective, constraints, resolved inputs, locked skill paths, prior phase results, and required outputs.")
	fmt.Fprintln(stdout, "11. Require each phase sub-agent to return a structured report containing all outputs requested by that phase.")
	fmt.Fprintln(stdout, "12. Close each phase sub-agent immediately after its structured report is collected and stored.")
	fmt.Fprintln(stdout, "13. Store the run artifacts under `.loop/runs/yyyy/mm/dd/hh/mm`.")
	fmt.Fprintln(stdout, "14. Collect phase outputs and summarize the final result for the user.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Input Handling")
	fmt.Fprintln(stdout, "- Treat `spec.inputs` as the contract for what the loop needs.")
	fmt.Fprintln(stdout, "- Map obvious user-provided values, such as a Jira ticket id, to matching inputs.")
	fmt.Fprintln(stdout, "- Ask the user when a required input is missing or ambiguous.")
	fmt.Fprintln(stdout, "- Do not invent missing input values.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Phase Execution")
	fmt.Fprintln(stdout, "- The main agent is the orchestrator; it does not run phase work directly or blur phases into one long task.")
	fmt.Fprintln(stdout, "- Use one sub-agent per phase when the environment supports sub-agents.")
	fmt.Fprintln(stdout, "- Do not pass the raw loop YAML as the sub-agent prompt.")
	fmt.Fprintln(stdout, "- Derive the sub-agent role from the phase context, such as expert in architecture, security, QA, product, data, or another domain named by the phase.")
	fmt.Fprintln(stdout, "- Keep phase boundaries explicit: give each sub-agent only the strict prompt for its phase, resolved inputs, and relevant previous outputs.")
	fmt.Fprintln(stdout, "- Tell each sub-agent which outputs the phase requires and require a structured report with those outputs.")
	fmt.Fprintln(stdout, "- Close the sub-agent after the phase is done; do not keep phase sub-agents open across phases.")
	fmt.Fprintln(stdout, "- Preserve evidence and handoffs between phases so the next phase can continue from verified results.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Run Artifacts")
	fmt.Fprintln(stdout, "- Create one run directory per execution:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm`")
	fmt.Fprintln(stdout, "- Store the exact loop definition as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/loop.yml`")
	fmt.Fprintln(stdout, "- Store each phase prompt as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/phase_{idx++}_name.md`")
	fmt.Fprintln(stdout, "- Store the final machine-readable run report as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/report.json`")
	fmt.Fprintln(stdout, "- `report.json` must include the run summary, resolved inputs, every phase report, and only outputs defined by each phase plus orchestrator-tracked `status` and `duration_in_seconds`.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Output Semantics")
	fmt.Fprintln(stdout, "- `pull` writes artifacts under `.agents/` and records `.agents/agentkit.lock.json`.")
	fmt.Fprintln(stdout, "- Loop artifacts are installed under `.agents/loops/<loop-name>/<version>/loop.yml` and mirrored to `.agents/loops/<loop-name>/loop.yml` for compatibility.")
	fmt.Fprintln(stdout, "- Skill dependencies are installed under `.agents/skills/<skill-name>/<version>/` and mirrored to `.agents/skills/<skill-name>/` for compatibility.")
	fmt.Fprintln(stdout, "- Repeated pulls skip artifacts whose locked digest is already current.")
}
