package main

import (
	"fmt"
	"io"
)

func printQuickstart(stdout io.Writer, _ options) {
	fmt.Fprintln(stdout, "loop - OCI-backed YAML loop packages")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Package a YAML file as an OCI artifact, push it to a Docker-compatible registry, pull it into a local cache, and display it later.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "GETTING STARTED")
	fmt.Fprintln(stdout, "  loop init")
	fmt.Fprintln(stdout, "      Add loop agent instructions to AGENTS.md.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  loop validate ./loop.yml")
	fmt.Fprintln(stdout, "      Validate ./loop.yml against the embedded loop schema.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  loop render ./loop.yml")
	fmt.Fprintln(stdout, "      Display the loop phases, transitions, and escalations as a terminal flowchart.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  loop push ./loop.yml ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Validate ./loop.yml, package it as an OCI artifact, and push it.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  loop pull ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Pull the package into the local cache. Output looks like docker pull.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  loop run ghcr.io/owner/repo/package:tag")
	fmt.Fprintln(stdout, "      Print the YAML. If it is not cached, pull it first.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "REGISTRY LOGIN")
	fmt.Fprintln(stdout, "  docker login ghcr.io")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "  Or use non-interactive environment variables:")
	fmt.Fprintln(stdout, "      export GHCR_USERNAME=<github-user-or-org>")
	fmt.Fprintln(stdout, "      export GHCR_TOKEN=<token-with-read-or-write-packages>")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "REFERENCE FORMAT")
	fmt.Fprintln(stdout, "  registry/namespace/package_name:tag")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "EXAMPLES")
	fmt.Fprintln(stdout, "  loop init")
	fmt.Fprintln(stdout, "  loop validate ./test.yml")
	fmt.Fprintln(stdout, "  loop render ./test.yml")
	fmt.Fprintln(stdout, "  loop push ./test.yml ghcr.io/arkham-advisory/test-loophub/test:0.1.0")
	fmt.Fprintln(stdout, "  loop pull ghcr.io/arkham-advisory/test-loophub/test:0.1.0")
	fmt.Fprintln(stdout, "  loop run ghcr.io/arkham-advisory/test-loophub/test:0.1.0")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "AGENT CONTEXT")
	fmt.Fprintln(stdout, "  Run `loop prime` for agent-oriented workflow instructions.")
}

func printPrime(stdout io.Writer, _ options) {
	fmt.Fprintln(stdout, "# Loop Agent Quickstart")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Use this context when a user asks an agent to run a loop from an OCI package.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Agent Role")
	fmt.Fprintln(stdout, "- The main agent is an orchestrator only.")
	fmt.Fprintln(stdout, "- Read the loop from the CLI output and execute it as the instruction source for the run.")
	fmt.Fprintln(stdout, "- Do not perform independent exploration, repository changes, file edits, or phase work yourself.")
	fmt.Fprintln(stdout, "- Only perform actions needed to complete the orchestrator role: pull and read the loop, resolve inputs, prepare phase prompts, dispatch sub-agents, store run artifacts, and summarize results.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Orchestrator Responsibilities")
	fmt.Fprintln(stdout, "- Coordinate the loop, manage phase state, and ensure required actions happen in the correct order.")
	fmt.Fprintln(stdout, "- Track default phase outputs for every phase: `status` as one of `completed`, `blocked`, or `escalated`, and `duration_in_seconds` as a number.")
	fmt.Fprintln(stdout, "- Update each phase status and duration as the loop progresses.")
	fmt.Fprintln(stdout, "- Ensure the loop progresses smoothly, required actions are completed, and issues or ambiguities are escalated appropriately.")
	fmt.Fprintln(stdout, "- Collect outputs from each phase and make them available for review and analysis.")
	fmt.Fprintln(stdout, "- Do not make decisions on behalf of sub-agents; provide context, information, guidance, resources, documentation, and support so sub-agents can make informed decisions.")
	fmt.Fprintln(stdout, "- Do not review, implement, or change the codebase yourself; ensure the right sub-agent has the resources and instructions needed to do that phase.")
	fmt.Fprintln(stdout, "- Add a `summary` section to the final report containing `status`, `objective`, `outcome`, and `duration_in_seconds`.")
	fmt.Fprintln(stdout, "- Ensure each phase report contains only outputs defined by that phase, plus the orchestrator-tracked `status` and `duration_in_seconds`.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Reference Format")
	fmt.Fprintln(stdout, "- A loop package reference must be tagged:")
	fmt.Fprintln(stdout, "  `registry/namespace/package_name:tag`")
	fmt.Fprintln(stdout, "- Example:")
	fmt.Fprintln(stdout, "  `ghcr.io/arkham-advisory/test-loophub/test:0.1.0`")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Authentication")
	fmt.Fprintln(stdout, "- Prefer existing Docker credentials:")
	fmt.Fprintln(stdout, "  `docker login ghcr.io`")
	fmt.Fprintln(stdout, "- In non-interactive environments, set credentials before using the CLI:")
	fmt.Fprintln(stdout, "  `export GHCR_USERNAME=<github-user-or-org>`")
	fmt.Fprintln(stdout, "  `export GHCR_TOKEN=<token-with-read-packages>`")
	fmt.Fprintln(stdout, "- In GitHub Actions, `GITHUB_ACTOR` and `GITHUB_TOKEN` are used when `GHCR_*` is not set and the package grants access.")
	fmt.Fprintln(stdout, "- If GHCR returns 403, the token probably lacks package read access or SSO authorization.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Essential Commands")
	fmt.Fprintln(stdout, "- Pull a loop package into the local cache. This prints Docker-like status and does not print YAML:")
	fmt.Fprintln(stdout, "  `loop pull ghcr.io/owner/repo/package:tag`")
	fmt.Fprintln(stdout, "- Display the loop YAML. If the package is not cached, this pulls it first:")
	fmt.Fprintln(stdout, "  `loop run ghcr.io/owner/repo/package:tag`")
	fmt.Fprintln(stdout, "- Copy the cached YAML to a file:")
	fmt.Fprintln(stdout, "  `loop pull --output loop.yml ghcr.io/owner/repo/package:tag`")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Agent Workflow")
	fmt.Fprintln(stdout, "1. Extract the OCI reference and any provided context from the user request.")
	fmt.Fprintln(stdout, "2. Ensure registry authentication is available before pulling private packages.")
	fmt.Fprintln(stdout, "3. Run `loop pull <ref>` to cache the package and verify access.")
	fmt.Fprintln(stdout, "4. Run `loop run <ref>` to print the YAML loop definition; treat that YAML as the execution instructions.")
	fmt.Fprintln(stdout, "5. Inspect `spec.inputs` before starting the loop.")
	fmt.Fprintln(stdout, "6. Resolve every input from the user request, existing conversation context, or explicit defaults in the loop definition.")
	fmt.Fprintln(stdout, "7. Ask the user for any missing required input values before running phases.")
	fmt.Fprintln(stdout, "8. Start the loop only after all required inputs are known.")
	fmt.Fprintln(stdout, "9. Act as the orchestrator: for each phase, craft a strict and guided sub-agent prompt from the phase context, such as `act as an expert in <domain>`, with the exact objective, constraints, resolved inputs, prior phase results, and required outputs.")
	fmt.Fprintln(stdout, "10. Require each phase sub-agent to return a structured report containing all outputs requested by that phase.")
	fmt.Fprintln(stdout, "11. Close each phase sub-agent immediately after its structured report is collected and stored.")
	fmt.Fprintln(stdout, "12. Store the run artifacts under `.loop/runs/yyyy/mm/dd/hh/mm`.")
	fmt.Fprintln(stdout, "13. Collect phase outputs and summarize the final result for the user.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Input Handling")
	fmt.Fprintln(stdout, "- Treat `spec.inputs` as the contract for what the loop needs.")
	fmt.Fprintln(stdout, "- Map obvious user-provided values, such as a Jira ticket id, to matching inputs.")
	fmt.Fprintln(stdout, "- Ask the user when a required input is missing or ambiguous.")
	fmt.Fprintln(stdout, "- Do not invent missing input values.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Phase Execution")
	fmt.Fprintln(stdout, "- The main agent is the orchestrator; it does not run phase work directly or blur phases into one long task.")
	fmt.Fprintln(stdout, "- Use one sub-agent per phase when the environment supports sub-agents.")
	fmt.Fprintln(stdout, "- Do not pass the raw loop YAML as the sub-agent prompt.")
	fmt.Fprintln(stdout, "- Derive the sub-agent role from the phase context, such as expert in architecture, security, QA, product, data, or another domain named by the phase.")
	fmt.Fprintln(stdout, "- Keep phase boundaries explicit: give each sub-agent only the strict prompt for its phase, resolved inputs, and relevant previous outputs.")
	fmt.Fprintln(stdout, "- Tell each sub-agent which outputs the phase requires and require a structured report with those outputs.")
	fmt.Fprintln(stdout, "- Close the sub-agent after the phase is done; do not keep phase sub-agents open across phases.")
	fmt.Fprintln(stdout, "- Preserve evidence and handoffs between phases so the next phase can continue from verified results.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Run Artifacts")
	fmt.Fprintln(stdout, "- Create one run directory per execution:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm`")
	fmt.Fprintln(stdout, "- Store the exact loop definition as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/loop.yml`")
	fmt.Fprintln(stdout, "- Store each phase prompt as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/phase_{idx++}_name.md`")
	fmt.Fprintln(stdout, "- Store the final machine-readable run report as:")
	fmt.Fprintln(stdout, "  `.loop/runs/yyyy/mm/dd/hh/mm/report.json`")
	fmt.Fprintln(stdout, "- `report.json` must include the run summary, resolved inputs, every phase report, and only outputs defined by each phase plus orchestrator-tracked `status` and `duration_in_seconds`.")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "## Output Semantics")
	fmt.Fprintln(stdout, "- `pull` behaves like `docker pull`: status lines only.")
	fmt.Fprintln(stdout, "- `run` prints the YAML content to stdout.")
	fmt.Fprintln(stdout, "- Repeated pulls use the local cache when the remote layer digest matches.")
}
